
development:
  adapter: postgresql
  database: giveforward_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: giveforward_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: giveforward_production
  pool: 5
  timeout: 5000
